name : Mi primer action :)

on : 
  push:
      branches: ["main"]
      
jobs:
  saludo:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensajes
        run: echo "Mi primer mensaje :)"
      - name: Fallo intencionado
        run: exit 1
      - name: Checkout del codido
        uses: actions/checkout@v4

      - name: Usar Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Construir app con node
        run: npm install

      - name: Verificar si existe app.js
        run: |
          if[ !-f"$GITHUB_WORKSPACE/app.js" ]; then 
            echo "No encontre app.js :("
            exit 1
          fi
          echo "Si encontre app.js :)"
