name : Mi primer action :)

on : 
  push:
      branches: ["main"]
      
jobs:
  saludo:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensajes
        run: echo "Mi primer mensaje :)"
      - name: Fallo intencionado
        run: exit 1
